### ISSUE TITLE
plugin.yml non existant

### ISSUE THREAD

**Issue by robertjones6** [DenizenScript/Denizen-Core#42]
I seem to be getting this error

[18:34:11] [Server thread/ERROR]: Could not load 'plugins/denizencore-1.10.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot_1.9_latest.jar:git-Spigot-095e59a-2bfda1f]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot_1.9_latest.jar:git-Spigot-095e59a-2bfda1f]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot_1.9_latest.jar:git-Spigot-095e59a-2bfda1f]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot_1.9_latest.jar:git-Spigot-095e59a-2bfda1f]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot_1.9_latest.jar:git-Spigot-095e59a-2bfda1f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more

**Comment by Morphan1** [comment]
I don't know why or how you got the DenizenCore, but that's not a plugin. Download the plugin from here http://ci.mineconomy.org/job/Denizen_Developmental/lastSuccessfulBuild/
